### ISSUE TITLE
[Android] No code detected

### ISSUE THREAD

**Issue by Sirfanas** [kivy-garden/zbarcam#25]
Hi,
Since the last update to upgrade zbarcam to kivy 1.11.1 I can't use scanner anymore,
The app compile without problem, my scanner start but it doesn't detect any QRCode / Barcode

Here is my requirements
```
requirements =
  plyer,
  certifi,
  openssl,
  pyjnius,
  android,
  kivy==1.11.1,
  libiconv,
  libzbar,
  Pillow==5.2.0,
  python3,
  pyzbar==0.1.8,
  zbarcam
```.

Did I miss something ?
Thank's

**Comment by AndreMiras** [comment]
Yes I would recommend you to make sure you're running `zbarcam==2019.0910`
So pin this version in your requirements and start from a very clean build.
If you're using buildozer, you can check what version was running by doing a:
```sh
cat .buildozer/android/platform/build/build/python-installs/*/kivy_garden/zbarcam/version.py
```
If this doesn't work for you, we can try to build an apk for you to test on your device. We're in the process of integrating it to F-Droid so that would make it easier https://gitlab.com/fdroid/fdroiddata/merge_requests/5395

**Comment by Sirfanas** [comment]
Perfect !
Thank's a lot !
Also, you may check your buildozer.spec, I have to put xcamera in garden_requirements AND in requirements
Otherwise it's not working for me
